name: Actions testing

env: 
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
  REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  Z_IMAGE_TAGS: s390x-${{ github.sha }}
  X_IMAGE_TAGS: amd64-${{ github.sha }}
  MANIFEST_IMAGE_TAG: manifest-${{ github.sha }}
  ROX_CENTRAL_ADDRESS: ${{ secrets.ROX_ADDRESS }}
  ROX_API_TOKEN: ${{ secrets.ROX_API_TOKEN }}

  IMAGE_REGISTRY: quay.io/mmondics
  APP_NAME: nationalparks
  MANIFEST_NAME: nationalparks-manifest
  
  SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  
on: workflow_dispatch # run action manually
#on: push # run action on any push

jobs:

  acs-image-scan: 
    name: Scan container manifest with Red Hat Advanced Cluster Security
    runs-on: [self-hosted, linux, x64]
    environment: openshift
    continue-on-error: true
    
    steps:
    - name: install roxctl cli        
      run: | 
        curl -O https://mirror.openshift.com/pub/rhacs/assets/4.1.0/bin/Linux/roxctl
        chmod +x roxctl
    - name: deployment-check
      run: |
        ./roxctl --insecure-skip-tls-verify deployment check --endpoint ${{ env.ROX_CENTRAL_ADDRESS }} -f yaml/combined/national-parks-combined.yaml 2>&1 | tee deployment_check.txt
    - name: image-scan
      run: |
        ./roxctl --insecure-skip-tls-verify image scan --endpoint ${{ env.ROX_CENTRAL_ADDRESS }} --image quay.io/centos7/httpd-24-centos7:centos7 2>&1 | tee image_scan.json
    - name: image-check
      run: |
        ./roxctl --insecure-skip-tls-verify image check --endpoint ${{ env.ROX_CENTRAL_ADDRESS }} --image quay.io/centos7/httpd-24-centos7:centos7 2>&1 | tee image_check.txt
    - name: Send email 
      # You may pin to the exact commit or the version.
      # uses: dawidd6/action-send-mail@fa73d6accd067d4151b71f124ed939da15097abf
      uses: dawidd6/action-send-mail@v3.7.2
      with:
        # Connection URL protocol://user:password@server:port, protocol can be smtp or smtp+starttls, replaces server_address, server_port, secure, username and password
        #connection_url: # optional
        # SMTP server address
        server_address: smtp.gmail.com
        # SMTP server port
        server_port: 465
        # Whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Authenticate as this user to SMTP server
        username: ${{ env.SMTP_USERNAME }}
        # Authenticate with this password to SMTP server
        password: ${{ env.SMTP_PASSWORD }}
        # Subject of mail message
        subject: Security Scan for quay.io/centos7/httpd-24-centos7:centos7
        # Recipients mail addresses (separated with comma)
        to: matt.mondics@ibm.com
        # Full name of mail sender (might be with an email address specified in <>)
        from: Matt Mondics <matt.mondics@ibm.com>
        # Body of mail message (might be a filename prefixed with file:// to read from)
        body: See attachments for deployment check, image check, and image scan
        # HTML body of mail message (might be a filename prefixed with file:// to read from)
        #html_body: # optional
        # Carbon copy recipients (separated with comma)
        #cc: # optional
        # Blind carbon copy recipients (separated with comma)
        #bcc: # optional
        # An email address that will appear on the Reply-To field
        #reply_to: # optional
        # The Message-ID this message is replying to
        #in_reply_to: # optional
        # Allow unsigned/invalid certificates
        #ignore_cert: # optional
        # Convert body from Markdown to HTML (set content_type input as text/html too)
        #convert_markdown: # optional
        # Files that will be added to mail message attachments (separated with comma)
        attachments: deployment_check.txt, image_scan.json, image_check.txt
